Repository WildCodeSchool/orleans-php-202009-project-ideoz, pull requests merged in 2020-12, with the labels that each got.

#2 S00 initialization
  .gitignore
  assets/styles/app.scss
  assets/styles/variables.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  yarn.lock
Labels: Corrections done, Reviewed

#3 dev to master
  .gitignore
  assets/styles/app.scss
  assets/styles/variables.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  yarn.lock
Labels: Reviewed

#18 S01 initialization fix
  .gitignore
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/variables.scss
  package.json
  templates/base.html.twig
  yarn.lock
Labels: Reviewed

#22 service section on home page
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  migrations/Version20201209085858.php
  src/Controller/HomeController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/OfferFixtures.php
  src/Entity/Offer.php
  src/Repository/OfferRepository.php
  symfony.lock
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed

#24 dev to master
  .gitignore
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  migrations/Version20201209085858.php
  package.json
  src/Controller/HomeController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/OfferFixtures.php
  src/Entity/Offer.php
  src/Repository/OfferRepository.php
  symfony.lock
  templates/base.html.twig
  templates/home/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#23 Made the Navbar
  .gitignore
  assets/images/logo.png
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/base.html.twig
  templates/includes/_mobilebanner.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
Labels: Reviewed

#19 create footer
  assets/images/facebook.png
  assets/images/linkedin.png
  assets/images/twitter.png
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/footer.scss
  migrations/Version20201209103432.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Company.php
  src/Repository/CompanyRepository.php
  templates/_footer.html.twig
  templates/base.html.twig
  templates/layout.html.twig
Labels: Reviewed

#25 dev to master
  .gitignore
  assets/images/facebook.png
  assets/images/linkedin.png
  assets/images/logo.png
  assets/images/twitter.png
  assets/js/app.js
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/variables.scss
  migrations/Version20201209103432.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Company.php
  src/Repository/CompanyRepository.php
  templates/_footer.html.twig
  templates/base.html.twig
  templates/includes/_mobilebanner.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
  templates/layout.html.twig
Labels: Reviewed

#39 add hover effect on service section on homepage
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
Labels: Reviewed

#30 Us04 temoignage for homepage
  assets/images/150.png
  assets/styles/home.scss
  assets/styles/variables.scss
  migrations/Version20201209085858.php
  migrations/Version20201209103432.php
  migrations/Version20201215092848.php
  src/Controller/HomeController.php
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/TestimonyFixtures.php
  src/Entity/Ecosystem.php
  src/Entity/Testimony.php
  src/Repository/EcosystemRepository.php
  src/Repository/TestimonyRepository.php
  templates/home/index.html.twig
Labels: Corrections done, Reviewed

#41 Fix navbar
  assets/styles/app.scss
  assets/styles/variables.scss
  composer.lock
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
  templates/layout.html.twig
Labels: Reviewed

#42 fix footer
  templates/_footer.html.twig
Labels: Reviewed

#44 add ecosystem section on homepage
  assets/styles/home.scss
  src/Controller/HomeController.php
  src/DataFixtures/EcosystemeFixtures.php
  templates/home/index.html.twig
Labels: Reviewed

#47 S02 us28 contact button homepage
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#52 dev to master
  .github/workflows/main.yml
  .gitignore
  assets/images/150.png
  assets/images/doublequotes2.png
  assets/images/doublequotes3.png
  assets/images/quotes.svg
  assets/images/shakinghands.jpg
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/testimony.scss
  assets/styles/variables.scss
  composer.lock
  migrations/Version20201209085858.php
  migrations/Version20201209103432.php
  migrations/Version20201215092848.php
  src/Controller/HomeController.php
  src/Controller/TestimonyController.php
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/TestimonyFixtures.php
  src/Entity/Ecosystem.php
  src/Entity/Testimony.php
  src/Repository/EcosystemRepository.php
  src/Repository/TestimonyRepository.php
  templates/_footer.html.twig
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
  templates/layout.html.twig
  templates/testimonies/testimonies.html.twig
  webpack.config.js
Labels: Reviewed

#51 US12_ Index/Show_Testimony
  .github/workflows/main.yml
  composer.lock
  config/packages/twig.yaml
  src/Controller/TestimonyController.php
  templates/adminTestimony/index.html.twig
Labels: Corrections done, Reviewed

#54 VIIIIIIITE (dev -> master)
  .github/workflows/main.yml
  assets/styles/app.scss
  composer.lock
  config/packages/twig.yaml
  src/Controller/TestimonyController.php
  templates/adminTestimony/index.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
Labels: Reviewed

#55 Us10 edit_testimony
  src/Controller/TestimonyController.php
  src/Form/TestimonyType.php
  templates/adminTestimony/_form.html.twig
  templates/adminTestimony/edit.html.twig
Labels: Reviewed

#58 fix bug stylesheet
  assets/js/app.js
  assets/styles/home.scss
  assets/styles/testimony.scss
  templates/base.html.twig
Labels: Reviewed

#59 change some css
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
Labels: Reviewed

#60 S03 us08 testimony contact
  assets/styles/testimony.scss
  src/Controller/TestimonyController.php
  templates/testimonies/testimonies.html.twig
Labels: Reviewed

#56 Us09 new_testimony
  src/Controller/TestimonyController.php
  templates/adminTestimony/new.html.twig
Labels: Conflicts resolved, Reviewed

#57 Us11 delete_testimony
  src/Controller/TestimonyController.php
  templates/adminTestimony/_delete_form.html.twig
Labels: Conflicts resolved, Reviewed

#61 fix ecosystem section
  assets/js/home.js
  assets/styles/home.scss
  assets/styles/variables.scss
  migrations/Version20201227141748.php
  src/Controller/HomeController.php
  src/DataFixtures/EcosystemeFixtures.php
  src/Entity/Ecosystem.php
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed
