Repository WildCodeSchool/orleans-php-202009-project-ideoz, pull requests merged in 2021-01, with the labels that each got.

#73 fix route admin + a little css
  src/Controller/TestimonyController.php
  templates/adminTestimony/_delete_form.html.twig
  templates/adminTestimony/edit.html.twig
  templates/adminTestimony/index.html.twig
  templates/adminTestimony/new.html.twig
Labels: Reviewed

#72 S03 us18 read ecosystem
  assets/styles/adminEcosystem.scss
  assets/styles/app.scss
  config/packages/translation.yaml
  migrations/Version20201229113316.php
  migrations/Version20201229114218.php
  src/Controller/AdminEcosystemController.php
  src/Controller/HomeController.php
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/Entity/Ecosystem.php
  src/Entity/Status.php
  src/Form/EcosystemType.php
  src/Repository/StatusRepository.php
  templates/admin/ecosystem/_delete_form.html.twig
  templates/admin/ecosystem/_form.html.twig
  templates/admin/ecosystem/edit.html.twig
  templates/admin/ecosystem/index.html.twig
  templates/admin/ecosystem/new.html.twig
  templates/admin/ecosystem/show.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#80 S04 us19 add ecosystem
  assets/styles/adminEcosystem.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210105144337.php
  src/Controller/AdminEcosystemController.php
  src/Entity/Ecosystem.php
  src/Form/EcosystemType.php
  symfony.lock
  templates/admin/ecosystem/_form.html.twig
  templates/admin/ecosystem/index.html.twig
  templates/admin/ecosystem/new.html.twig
  templates/admin/ecosystem/show.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#81 delete ecosystem
  assets/styles/adminEcosystem.scss
  src/Controller/AdminEcosystemController.php
  templates/admin/ecosystem/_delete_form.html.twig
  templates/admin/ecosystem/index.html.twig
  templates/admin/ecosystem/show.html.twig
Labels: Reviewed

#82 dev to master
  assets/js/app.js
  assets/js/home.js
  assets/styles/adminEcosystem.scss
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/testimony.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/translation.yaml
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20201227141748.php
  migrations/Version20201229113316.php
  migrations/Version20201229114218.php
  migrations/Version20210105144337.php
  src/Controller/AdminEcosystemController.php
  src/Controller/HomeController.php
  src/Controller/TestimonyController.php
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/Entity/Ecosystem.php
  src/Entity/Status.php
  src/Form/EcosystemType.php
  src/Form/TestimonyType.php
  src/Repository/StatusRepository.php
  symfony.lock
  templates/admin/ecosystem/_delete_form.html.twig
  templates/admin/ecosystem/_form.html.twig
  templates/admin/ecosystem/edit.html.twig
  templates/admin/ecosystem/index.html.twig
  templates/admin/ecosystem/new.html.twig
  templates/admin/ecosystem/show.html.twig
  templates/adminTestimony/_delete_form.html.twig
  templates/adminTestimony/_form.html.twig
  templates/adminTestimony/edit.html.twig
  templates/adminTestimony/index.html.twig
  templates/adminTestimony/new.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
  templates/testimonies/testimonies.html.twig
  webpack.config.js
Labels: Reviewed

#83 made crud and works on edit part of it
  assets/styles/adminOffer.scss
  src/Controller/AdminOfferController.php
  src/Entity/Offer.php
  src/Form/OfferType.php
  templates/adminOffer/_delete_form.html.twig
  templates/adminOffer/_form.html.twig
  templates/adminOffer/edit.html.twig
  templates/adminOffer/index.html.twig
  templates/adminOffer/new.html.twig
  templates/adminOffer/show.html.twig
  webpack.config.js
Labels: Reviewed

#84 change some bootstrap
  templates/testimonies/testimonies.html.twig
Labels: Reviewed

#85 Fix navbar
  assets/styles/app.scss
  templates/base.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
Labels: Reviewed

#86 Fix Footer
  templates/_footer.html.twig
  templates/base.html.twig
Labels: Reviewed

#87 edit ecosystem
  src/Controller/AdminEcosystemController.php
  templates/admin/ecosystem/_delete_form.html.twig
  templates/admin/ecosystem/edit.html.twig
Labels: Reviewed

#88 fix extend admin testimony
  templates/adminTestimony/edit.html.twig
  templates/adminTestimony/index.html.twig
  templates/adminTestimony/new.html.twig
Labels: Reviewed

#90 fix route
  src/Controller/AdminEcosystemController.php
  src/Controller/AdminOfferController.php
  src/Controller/TestimonyController.php
Labels: Reviewed

#91 fix button and chevrons
  assets/styles/app.scss
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#92 fix testimony page
  assets/styles/testimony.scss
  assets/styles/variables.scss
  templates/includes/_mobilebanner.html.twig
  templates/testimonies/testimonies.html.twig
Labels: Reviewed

#93 dev to master
  assets/styles/adminOffer.scss
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/testimony.scss
  assets/styles/variables.scss
  src/Controller/AdminEcosystemController.php
  src/Controller/AdminOfferController.php
  src/Controller/TestimonyController.php
  src/Entity/Offer.php
  src/Form/OfferType.php
  templates/_footer.html.twig
  templates/admin/ecosystem/_delete_form.html.twig
  templates/admin/ecosystem/edit.html.twig
  templates/adminOffer/_delete_form.html.twig
  templates/adminOffer/_form.html.twig
  templates/adminOffer/edit.html.twig
  templates/adminOffer/index.html.twig
  templates/adminOffer/new.html.twig
  templates/adminOffer/show.html.twig
  templates/adminTestimony/edit.html.twig
  templates/adminTestimony/index.html.twig
  templates/adminTestimony/new.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/includes/_mobilebanner.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
  templates/testimonies/testimonies.html.twig
  webpack.config.js
Labels: Reviewed

#89 Made contact form
  assets/images/contact.jpg
  assets/styles/contact.scss
  config/services.yaml
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  src/Repository/ContactRepository.php
  templates/baseEmail.html.twig
  templates/contact/contactEmail.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
  webpack.config.js
Labels: Reviewed

#97 add navbar admin
  templates/includes/_navbarAdmin.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed

#98 made the index part of the Offer crud
  src/Controller/AdminOfferController.php
  templates/adminOffer/_delete_form.html.twig
  templates/adminOffer/index.html.twig
  templates/adminOffer/new.html.twig
  templates/adminOffer/show.html.twig
Labels: Reviewed

#103 add offers in navbar via BDD
  assets/styles/app.scss
  src/Controller/HomeController.php
  templates/includes/_navbar.html.twig
  templates/includes/_navbarOffer.html.twig
  templates/includes/_navbarmobile.html.twig
Labels: Reviewed

#104 dev to master
  assets/images/contact.jpg
  assets/styles/app.scss
  assets/styles/contact.scss
  config/services.yaml
  src/Controller/AdminOfferController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  src/Repository/ContactRepository.php
  templates/adminOffer/_delete_form.html.twig
  templates/adminOffer/index.html.twig
  templates/adminOffer/new.html.twig
  templates/adminOffer/show.html.twig
  templates/baseEmail.html.twig
  templates/contact/contactEmail.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarAdmin.html.twig
  templates/includes/_navbarOffer.html.twig
  templates/includes/_navbarmobile.html.twig
  templates/layoutAdmin.html.twig
  webpack.config.js
Labels: Reviewed

#102 add filter on admin ecosystem index
  assets/styles/adminEcosystem.scss
  src/Controller/AdminEcosystemController.php
  src/Form/StatusFilterType.php
  templates/admin/ecosystem/index.html.twig
Labels: Corrections done, Reviewed

#99 made the show part of the crud
  assets/styles/adminOffer.scss
  templates/adminOffer/show.html.twig
Labels: Conflicts resolved, Reviewed

#101 Made about us section
  assets/images/binoculars.png
  assets/images/linkedin-blue.png
  assets/images/simon.png
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
Labels: Corrections done, Reviewed

#106 Fix admin
  src/Form/EcosystemType.php
  templates/admin/ecosystem/edit.html.twig
  templates/admin/ecosystem/show.html.twig
Labels: Reviewed

#107 add contact details in footer from BDD
  src/Controller/HomeController.php
  templates/includes/_footer.html.twig
  templates/includes/_footerContact.html.twig
  templates/layout.html.twig
Labels: Reviewed

#108 change logo admin testimony
  templates/adminOffer/edit.html.twig
  templates/adminTestimony/_delete_form.html.twig
  templates/adminTestimony/_form.html.twig
  templates/adminTestimony/edit.html.twig
  templates/adminTestimony/index.html.twig
  templates/adminTestimony/new.html.twig
Labels: Reviewed

#100 made the add part of the crud
  assets/styles/adminOffer.scss
  src/Controller/AdminOfferController.php
  templates/adminOffer/_form.html.twig
  templates/adminOffer/new.html.twig
Labels: Corrections done, Reviewed

#105 add the club co-oz part
  assets/images/CO-oz.png
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Corrections done, Reviewed

#109 Fix css
  assets/styles/adminTestimony.scss
  assets/styles/contact.scss
  templates/adminTestimony/_delete_form.html.twig
  templates/adminTestimony/_form.html.twig
  templates/adminTestimony/edit.html.twig
  templates/adminTestimony/index.html.twig
  templates/adminTestimony/new.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  webpack.config.js
Labels: Reviewed

#110 S05 us49 ckeditor
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  src/Form/EcosystemType.php
  src/Form/OfferType.php
  src/Form/TestimonyType.php
  symfony.lock
  templates/admin/ecosystem/show.html.twig
  templates/adminOffer/index.html.twig
  templates/adminOffer/show.html.twig
  templates/adminTestimony/index.html.twig
  templates/home/index.html.twig
  templates/testimonies/testimonies.html.twig
Labels: Conflicts resolved, Reviewed

#111 dev to master
  assets/images/CO-oz.png
  assets/images/binoculars.png
  assets/images/linkedin-blue.png
  assets/images/simon.png
  assets/styles/adminEcosystem.scss
  assets/styles/adminOffer.scss
  assets/styles/adminTestimony.scss
  assets/styles/app.scss
  assets/styles/contact.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/fos_ckeditor.yaml
  src/Controller/AdminEcosystemController.php
  src/Controller/AdminOfferController.php
  src/Controller/HomeController.php
  src/Form/EcosystemType.php
  src/Form/OfferType.php
  src/Form/StatusFilterType.php
  src/Form/TestimonyType.php
  symfony.lock
  templates/admin/ecosystem/edit.html.twig
  templates/admin/ecosystem/index.html.twig
  templates/admin/ecosystem/show.html.twig
  templates/adminOffer/_form.html.twig
  templates/adminOffer/edit.html.twig
  templates/adminOffer/index.html.twig
  templates/adminOffer/new.html.twig
  templates/adminOffer/show.html.twig
  templates/adminTestimony/_delete_form.html.twig
  templates/adminTestimony/_form.html.twig
  templates/adminTestimony/edit.html.twig
  templates/adminTestimony/index.html.twig
  templates/adminTestimony/new.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_footerContact.html.twig
  templates/layout.html.twig
  templates/testimonies/testimonies.html.twig
  webpack.config.js
Labels: Reviewed

#113 add a link
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
Labels: Reviewed

#114 GROS Fix bdd
  config/packages/vich_uploader.yaml
  migrations/Version20210111191842.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/CompetenceFixtures.php
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/LegalNoticeFixtures.php
  src/DataFixtures/ProjectFixtures.php
  src/Entity/Company.php
  src/Entity/Competence.php
  src/Entity/Ecosystem.php
  src/Entity/LegalNotice.php
  src/Entity/Project.php
  src/Repository/CompetenceRepository.php
  src/Repository/LegalNoticeRepository.php
  src/Repository/ProjectRepository.php
Labels: Reviewed

#115 add flash admin testi
  src/Controller/TestimonyController.php
Labels: Reviewed

#130 S05 us54 show project
  assets/styles/adminProject.scss
  src/Controller/AdminProjectController.php
  src/Entity/Project.php
  src/Form/ProjectType.php
  templates/admin/project/_delete_form.html.twig
  templates/admin/project/_form.html.twig
  templates/admin/project/edit.html.twig
  templates/admin/project/index.html.twig
  templates/admin/project/new.html.twig
  templates/admin/project/show.html.twig
  templates/includes/_navbarAdmin.html.twig
  webpack.config.js
Labels: Reviewed

#112 Made login form, User entity and users roles
  assets/images/laptop.jpg
  assets/styles/app.scss
  assets/styles/login.scss
  composer.lock
  config/packages/security.yaml
  migrations/Version20210110114024.php
  phpstan.neon
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
  templates/security/login.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#131 Fix upload
  .gitignore
  assets/js/app.js
  assets/styles/adminEcosystem.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  config/packages/vich_uploader.yaml
  package.json
  src/DataFixtures/EcosystemeFixtures.php
  src/Entity/Ecosystem.php
  src/Form/EcosystemType.php
  templates/admin/ecosystem/index.html.twig
  templates/admin/ecosystem/show.html.twig
  templates/home/index.html.twig
  templates/testimonies/testimonies.html.twig
  yarn.lock
Labels: Reviewed

#132 delete project
  src/Controller/AdminProjectController.php
  templates/admin/project/_delete_form.html.twig
Labels: Reviewed

#133 add project
  src/Controller/AdminProjectController.php
  templates/admin/project/_form.html.twig
  templates/admin/project/new.html.twig
Labels: Reviewed

#135 update project
  src/Controller/AdminProjectController.php
  templates/admin/project/edit.html.twig
Labels: Reviewed

#134 culb co-oz entreprises partenaires
  assets/images/moutains2.jpg
  assets/styles/companies.scss
  src/Controller/CooperativeController.php
  templates/cooperative/companies.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#136 Us48 index crud company
  src/Controller/AdminCompanyController.php
  src/Controller/HomeController.php
  src/Entity/Company.php
  templates/adminCompany/index.html.twig
Labels: Reviewed

#137 create admin homepage + add member section on it
  assets/styles/admin.scss
  src/Controller/AdminHomeController.php
  templates/admin/home/index.html.twig
  templates/includes/_navbarAdmin.html.twig
  webpack.config.js
Labels: Reviewed

#139 fix src img
  templates/cooperative/companies.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#140 crud legal notions + show
  assets/styles/adminLegalNotice.scss
  src/Controller/LegalNoticeController.php
  src/Entity/LegalNotice.php
  src/Form/LegalNoticeType.php
  templates/admin/legal_notice/_delete_form.html.twig
  templates/admin/legal_notice/_form.html.twig
  templates/admin/legal_notice/edit.html.twig
  templates/admin/legal_notice/index.html.twig
  webpack.config.js
Labels: Reviewed

#138 index competence
  src/Controller/CompetenceController.php
  templates/adminCompetence/index.html.twig
Labels: Reviewed

#142 Fix crud ecosystem
  assets/styles/adminEcosystem.scss
  src/Controller/AdminEcosystemController.php
  src/Controller/HomeController.php
  src/Form/EcosystemType.php
  templates/admin/ecosystem/index.html.twig
  templates/includes/_navbarAdmin.html.twig
Labels: Reviewed

#144 crud update legal notice
  src/Controller/LegalNoticeController.php
  templates/admin/legal_notice/_form.html.twig
  templates/admin/legal_notice/edit.html.twig
  templates/admin/legal_notice/index.html.twig
  templates/includes/_navbarAdmin.html.twig
Labels: Reviewed

#141 Made the project part of collaborative space
  assets/images/climb-2.jpg
  assets/styles/projects.scss
  src/Controller/CooperativeController.php
  templates/cooperative/projects.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#143 edit competence
  src/Controller/CompetenceController.php
  src/Form/CompetenceType.php
  templates/adminCompetence/_form.html.twig
  templates/adminCompetence/edit.html.twig
  templates/adminCompetence/index.html.twig
Labels: Corrections done, Reviewed

#146 add legal notice
  src/Controller/AdminLegalNoticeController.php
  src/Controller/LegalNoticeController.php
  templates/includes/_footer.html.twig
  templates/legal_notice/legalNotice.html.twig
Labels: Reviewed

#145 Fix testimony
  assets/styles/testimony.scss
  templates/testimonies/testimonies.html.twig
Labels: Corrections done, Reviewed

#147 new competence
  src/Controller/CompetenceController.php
  templates/adminCompetence/new.html.twig
Labels: Reviewed

#149 add links to navbars
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
Labels: Corrections done, Reviewed

#152 add a link to testimonies
  templates/home/index.html.twig
Labels: Reviewed

#153 Fix about us
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
Labels: Reviewed

#150 delete competence
  src/Controller/CompetenceController.php
  templates/adminCompetence/_delete_form.html.twig
Labels: Corrections done, Reviewed

#151 S03 us31 register form
  assets/images/laptop-registration.jpg
  assets/styles/register.scss
  composer.json
  composer.lock
  config/bundles.php
  migrations/Version20210118112111.php
  phpstan.neon
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#155 dev -> master
  assets/images/laptop-registration.jpg
  assets/styles/register.scss
  composer.json
  composer.lock
  config/bundles.php
  migrations/Version20210118112111.php
  phpstan.neon
  src/Controller/CompetenceController.php
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/adminCompetence/_delete_form.html.twig
  templates/home/index.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  webpack.config.js
Labels: Reviewed

#156 Edit Company
  src/Controller/AdminCompanyController.php
  src/Form/CompanyType.php
  templates/adminCompany/_form.html.twig
  templates/adminCompany/edit.html.twig
  templates/adminCompany/index.html.twig
Labels: Corrections done, Reviewed

#154 Made the relation between ecosystem and user entities
  migrations/Version20210119171748.php
  src/Entity/User.php
Labels: Conflicts resolved, Reviewed

#157 Fixed the header
  assets/styles/login.scss
  templates/security/login.html.twig
Labels: Corrections done, Reviewed

#158 Fix routes names and securized them
  config/packages/security.yaml
  src/Controller/AdminCompanyController.php
  src/Controller/CooperativeController.php
Labels: Corrections done, Reviewed

#159 Fix bdd
  migrations/Version20210120152444.php
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/Entity/Ecosystem.php
  src/Form/StatusFilterType.php
Labels: Reviewed

#160 Fixed block titles, spelling, removed some unexpected links and chang…
  templates/admin/ecosystem/edit.html.twig
  templates/admin/ecosystem/new.html.twig
  templates/admin/project/new.html.twig
  templates/admin/project/show.html.twig
  templates/adminCompany/index.html.twig
  templates/adminCompetence/edit.html.twig
  templates/adminCompetence/index.html.twig
  templates/adminCompetence/new.html.twig
  templates/adminOffer/edit.html.twig
  templates/adminOffer/index.html.twig
  templates/adminOffer/new.html.twig
  templates/adminOffer/show.html.twig
  templates/adminTestimony/edit.html.twig
  templates/adminTestimony/index.html.twig
  templates/adminTestimony/new.html.twig
  templates/base.html.twig
  templates/legal_notice/legalNotice.html.twig
  templates/testimonies/testimonies.html.twig
Labels: Reviewed

#161 Fixed handleEmailConfirmation() method
  src/Security/EmailVerifier.php
Labels: Reviewed

#162 S05 us17 search type
  src/Controller/CooperativeController.php
  src/Entity/Competence.php
  src/Entity/Ecosystem.php
  src/Entity/EcosystemSearch.php
  src/Entity/Project.php
  src/Form/EcosystemSearchType.php
  src/Repository/EcosystemRepository.php
  templates/cooperative/companies.html.twig
Labels: Reviewed

#163 dev to master
  assets/styles/login.scss
  config/packages/security.yaml
  migrations/Version20210119171748.php
  migrations/Version20210120152444.php
  src/Controller/AdminCompanyController.php
  src/Controller/CooperativeController.php
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/Entity/Competence.php
  src/Entity/Ecosystem.php
  src/Entity/EcosystemSearch.php
  src/Entity/Project.php
  src/Entity/User.php
  src/Form/CompanyType.php
  src/Form/EcosystemSearchType.php
  src/Form/StatusFilterType.php
  src/Repository/EcosystemRepository.php
  src/Security/EmailVerifier.php
  templates/admin/ecosystem/edit.html.twig
  templates/admin/ecosystem/new.html.twig
  templates/admin/project/new.html.twig
  templates/admin/project/show.html.twig
  templates/adminCompany/_form.html.twig
  templates/adminCompany/edit.html.twig
  templates/adminCompany/index.html.twig
  templates/adminCompetence/edit.html.twig
  templates/adminCompetence/index.html.twig
  templates/adminCompetence/new.html.twig
  templates/adminOffer/edit.html.twig
  templates/adminOffer/index.html.twig
  templates/adminOffer/new.html.twig
  templates/adminOffer/show.html.twig
  templates/adminTestimony/edit.html.twig
  templates/adminTestimony/index.html.twig
  templates/adminTestimony/new.html.twig
  templates/base.html.twig
  templates/cooperative/companies.html.twig
  templates/legal_notice/legalNotice.html.twig
  templates/security/login.html.twig
  templates/testimonies/testimonies.html.twig
Labels: Reviewed

#166 Changed roles
  config/packages/security.yaml
Labels: Reviewed

#165 add search by competences
  assets/styles/companies.scss
  src/Form/EcosystemSearchType.php
  src/Repository/EcosystemRepository.php
  templates/cooperative/companies.html.twig
Labels: Reviewed

#167 S05 us51 project
  assets/images/header_project.jpg
  assets/styles/projects.scss
  migrations/Version20210121103419.php
  src/Controller/CooperativeController.php
  src/Entity/Ecosystem.php
  src/Entity/User.php
  templates/base.html.twig
  templates/cooperative/projectEmail.html.twig
  templates/cooperative/projectSheet.html.twig
  templates/cooperative/projects.html.twig
Labels: Reviewed

#168 Fixed the "from" in the mail
  src/Controller/RegistrationController.php
Labels: Reviewed

#170 Fixed CSS on header homepage and rewrote "IDEOZ" in "IdeOZ"
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#164 fiche entreprise + mailpour mise en relation
  src/Controller/CooperativeController.php
  src/DataFixtures/EcosystemeFixtures.php
  templates/cooperative/companies.html.twig
  templates/cooperative/companyEmail.html.twig
  templates/cooperative/show_company.html.twig
Labels: Corrections done, Reviewed

#169 fix the projects
  assets/styles/projects.scss
  templates/cooperative/projects.html.twig
Labels: Corrections done, Reviewed

#172 S05 us23 offer
  assets/images/header_service1.jpg
  assets/images/header_service2.jpg
  assets/images/header_service3.jpg
  assets/images/photo_service1.jpg
  assets/images/photo_service2.jpg
  assets/images/photo_service3.jpg
  assets/styles/offer.scss
  migrations/Version20210121132324.php
  src/Controller/OfferController.php
  src/DataFixtures/OfferFixtures.php
  src/Entity/Offer.php
  templates/includes/_navbarOffer.html.twig
  templates/offer/index.html.twig
  webpack.config.js
Labels: Reviewed

#173 fix homepage
  assets/styles/app.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
Labels: Reviewed

#174 fix testimony
  assets/images/150.png
  assets/images/doublequotes2.png
  assets/images/doublequotes3.png
  assets/images/header_testimony.jpg
  assets/images/shakinghands.jpg
  assets/images/yellow_quotes.png
  assets/styles/testimony.scss
  templates/testimonies/testimonies.html.twig
Labels: Reviewed

#175 fix footer
  templates/includes/_footer.html.twig
Labels: Reviewed

#176 fix admin company
  src/Form/CompanyType.php
  templates/adminCompany/_form.html.twig
  templates/adminCompany/edit.html.twig
  templates/adminCompany/index.html.twig
Labels: Reviewed

#177 fix admin competence
  templates/adminCompetence/_delete_form.html.twig
  templates/adminCompetence/_form.html.twig
  templates/adminCompetence/edit.html.twig
  templates/adminCompetence/index.html.twig
  templates/adminCompetence/new.html.twig
Labels: Reviewed

#178 fix admin testimony
  src/Controller/TestimonyController.php
  src/Form/TestimonyType.php
  templates/adminTestimony/_delete_form.html.twig
Labels: Reviewed

#179 S06 user profile
  assets/images/profile.jpg
  assets/styles/profile.scss
  src/Controller/AdminEcosystemController.php
  src/Controller/SecurityController.php
  src/Entity/Ecosystem.php
  src/Form/MembershipType.php
  templates/includes/_navbar.html.twig
  templates/security/membershipForm.html.twig
  templates/security/profile.html.twig
  webpack.config.js
Labels: Reviewed

#181 fix admin ecosystem
  src/Controller/AdminEcosystemController.php
  src/Form/EcosystemType.php
  templates/admin/ecosystem/index.html.twig
Labels: Reviewed

#182 fix admin project
  assets/styles/adminProject.scss
  src/Form/ProjectType.php
  templates/admin/project/show.html.twig
Labels: Reviewed

#183 fix legal notice
  assets/styles/adminLegalNotice.scss
  templates/admin/legal_notice/index.html.twig
  templates/legal_notice/legalNotice.html.twig
Labels: Reviewed

#184 fix admin service
  assets/styles/adminOffer.scss
  templates/adminOffer/_form.html.twig
  templates/adminOffer/edit.html.twig
  templates/adminOffer/index.html.twig
  templates/adminOffer/show.html.twig
Labels: Reviewed

#186 Fixed some flash messages and Bootstrap classes
  src/Controller/RegistrationController.php
  templates/registration/register.html.twig
Labels: Reviewed

#180 S07 us37 forgotten password
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  migrations/Version20210123222804.php
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
Labels: Corrections done, Reviewed

#187 Fix projects
  assets/styles/projects.scss
  src/Controller/CooperativeController.php
  templates/cooperative/projectSheet.html.twig
  templates/cooperative/projects.html.twig
Labels: Reviewed

#190 fix display companies espace cooz
  assets/styles/companies.scss
  src/Controller/CooperativeController.php
  templates/cooperative/companies.html.twig
Labels: Reviewed

#188 Fixed authorization for the cooperative space
  config/packages/security.yaml
  src/Controller/CooperativeController.php
Labels: Conflicts resolved, Reviewed

#193 Fix service
  assets/styles/adminOffer.scss
  src/Entity/Offer.php
  src/Form/OfferType.php
  templates/home/index.html.twig
Labels: Reviewed

#195 Fix fiche entreprise
  templates/cooperative/show_company.html.twig
Labels: Reviewed

#196 Fixed titles
  templates/admin/legal_notice/edit.html.twig
  templates/admin/project/edit.html.twig
  templates/adminCompetence/index.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/membershipForm.html.twig
Labels: Reviewed

#197 Fix navbar
  assets/styles/app.scss
  templates/includes/_navbar.html.twig
  templates/includes/_navbarAdmin.html.twig
  templates/includes/_navbarmobile.html.twig
Labels: Reviewed

#198 Fix request controller
  src/Controller/AdminCompanyController.php
  src/Controller/AdminEcosystemController.php
  src/Controller/AdminOfferController.php
  src/Controller/CompetenceController.php
  src/Controller/CooperativeController.php
  templates/adminCompany/index.html.twig
Labels: Reviewed

#199 Fixed route language, regexs and methods for parameters
  src/Controller/AdminCompanyController.php
  src/Controller/AdminEcosystemController.php
  src/Controller/AdminHomeController.php
  src/Controller/AdminLegalNoticeController.php
  src/Controller/AdminOfferController.php
  src/Controller/AdminProjectController.php
  src/Controller/CompetenceController.php
  src/Controller/ContactController.php
  src/Controller/CooperativeController.php
  src/Controller/HomeController.php
  src/Controller/LegalNoticeController.php
  src/Controller/RegistrationController.php
  src/Controller/ResetPasswordController.php
  src/Controller/SecurityController.php
  src/Controller/TestimonyController.php
Labels: Reviewed

#200 Fix ck editor
  config/packages/fos_ckeditor.yaml
  src/Form/CompanyType.php
  src/Form/EcosystemType.php
  src/Form/MembershipType.php
  src/Form/OfferType.php
  src/Form/StatusFilterType.php
  templates/admin/home/index.html.twig
  templates/admin/project/show.html.twig
  templates/adminCompany/index.html.twig
  templates/adminCompetence/index.html.twig
  templates/adminTestimony/index.html.twig
  templates/cooperative/companies.html.twig
  templates/cooperative/projectSheet.html.twig
  templates/cooperative/projects.html.twig
  templates/cooperative/show_company.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
  templates/security/profile.html.twig
  templates/testimonies/testimonies.html.twig
Labels: Reviewed

#201 add a placeholder
  src/Form/EcosystemSearchType.php
  src/Repository/EcosystemRepository.php
Labels: Reviewed

#204 Add a change password button
  templates/security/profile.html.twig
Labels: Reviewed

#205 Fixed the ecosystem entity hydration when user enters some information
  src/Controller/SecurityController.php
Labels: Reviewed

#202 add fields in form + change css labels + add links
  assets/styles/adminEcosystem.scss
  assets/styles/adminLegalNotice.scss
  assets/styles/adminProject.scss
  assets/styles/adminTestimony.scss
  src/Form/CompanyType.php
  src/Form/EcosystemType.php
  src/Form/MembershipType.php
  templates/admin/ecosystem/index.html.twig
  templates/admin/ecosystem/show.html.twig
  templates/admin/home/index.html.twig
Labels: Reviewed

#206 fix the mobilebanner border
  templates/includes/_mobilebanner.html.twig
Labels: Reviewed

#208 Fixed "email could not be found" error message
  src/Security/LoginFormAuthenticator.php
Labels: Reviewed

#210 Fix search type
  templates/cooperative/companies.html.twig
Labels: Reviewed

#211 Fix css
  assets/styles/app.scss
  assets/styles/companies.scss
  assets/styles/contact.scss
  assets/styles/home.scss
  assets/styles/login.scss
  assets/styles/offer.scss
  assets/styles/profile.scss
  assets/styles/projects.scss
  assets/styles/register.scss
  assets/styles/testimony.scss
  assets/styles/variables.scss
  templates/admin/ecosystem/edit.html.twig
  templates/admin/ecosystem/index.html.twig
  templates/admin/ecosystem/new.html.twig
  templates/admin/ecosystem/show.html.twig
  templates/admin/home/index.html.twig
  templates/admin/legal_notice/edit.html.twig
  templates/admin/legal_notice/index.html.twig
  templates/admin/project/edit.html.twig
  templates/admin/project/index.html.twig
  templates/admin/project/new.html.twig
  templates/admin/project/show.html.twig
  templates/adminCompany/edit.html.twig
  templates/adminCompany/index.html.twig
  templates/adminCompetence/edit.html.twig
  templates/adminCompetence/index.html.twig
  templates/adminCompetence/new.html.twig
  templates/adminOffer/edit.html.twig
  templates/adminOffer/index.html.twig
  templates/adminOffer/new.html.twig
  templates/adminOffer/show.html.twig
  templates/adminTestimony/edit.html.twig
  templates/adminTestimony/index.html.twig
  templates/adminTestimony/new.html.twig
  templates/cooperative/show_company.html.twig
Labels: Reviewed

#212 Fix controller
  src/Controller/AdminLegalNoticeController.php
  src/Controller/CooperativeController.php
Labels: Reviewed

#209 fix the button mon compte
  templates/includes/_navbarmobile.html.twig
Labels: Reviewed

#214 add an hr
  templates/cooperative/companies.html.twig
  templates/home/index.html.twig
  templates/testimonies/testimonies.html.twig
Labels: Reviewed

#217 fix fixtures
  src/DataFixtures/CompetenceFixtures.php
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/LegalNoticeFixtures.php
  src/DataFixtures/ProjectFixtures.php
  src/DataFixtures/TestimonyFixtures.php
  src/DataFixtures/UserFixtures.php
  templates/admin/home/index.html.twig
Labels: Reviewed

#218 add the favicon
  assets/images/Favicon.png
  assets/images/favicon.png
  templates/base.html.twig
Labels: Reviewed

#207 Add a button on the bottom of the homepage if user is logged in
  templates/home/index.html.twig
Labels: Corrections done, Reviewed

#216 add pagination index entreprise
  assets/styles/companies.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_paginator.yaml
  src/Controller/CooperativeController.php
  symfony.lock
  templates/cooperative/companies.html.twig
Labels: Corrections done, Reviewed

#215 add intersect-observer animations
  assets/styles/app.scss
  assets/styles/companies.scss
  assets/styles/contact.scss
  assets/styles/home.scss
  assets/styles/offer.scss
  assets/styles/projects.scss
  templates/contact/index.html.twig
  templates/cooperative/companies.html.twig
  templates/cooperative/projects.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
  templates/testimonies/testimonies.html.twig
Labels: Corrections done, Reviewed

#219 Fix club co oz
  assets/images/CO-oz.png
  assets/images/co.png
  assets/styles/home.scss
Labels: Reviewed

#220 dev to master
  assets/images/CO-oz.png
  assets/images/Favicon.png
  assets/images/co.png
  assets/images/favicon.png
  assets/styles/app.scss
  assets/styles/companies.scss
  assets/styles/contact.scss
  assets/styles/home.scss
  assets/styles/offer.scss
  assets/styles/projects.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_paginator.yaml
  src/Controller/CooperativeController.php
  src/DataFixtures/CompetenceFixtures.php
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/LegalNoticeFixtures.php
  src/DataFixtures/ProjectFixtures.php
  src/DataFixtures/TestimonyFixtures.php
  src/DataFixtures/UserFixtures.php
  symfony.lock
  templates/admin/home/index.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/cooperative/companies.html.twig
  templates/cooperative/projects.html.twig
  templates/home/index.html.twig
  templates/offer/index.html.twig
  templates/testimonies/testimonies.html.twig
Labels: Reviewed

#221 Change redirection to error message
  config/packages/security.yaml
  src/Controller/CooperativeController.php
Labels: Corrections done, Reviewed

#222 update readme and .env
  .env
  .gitignore
  README.md
  public/uploads/logos/.gitignore
Labels: Corrections done, Reviewed

#225 dev to master
  .env
  .gitignore
  README.md
  config/packages/security.yaml
  public/uploads/logos/.gitignore
  src/Controller/CooperativeController.php
Labels: Reviewed

#223 add page 401
  assets/images/bg.jpg
  templates/bundles/TwigBundle/Exception/error401.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed

#224 Error 404
  assets/images/bg.jpg
  public/uploads/favicon-6006f90c4bccc330410399.png
  templates/bundles/Twig/Bundle/Exception/error404.html.twig
  webpack.config.js
Labels: Conflicts resolved, Reviewed

#244 fix fixtures
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#245 remove add and delete to offers
  src/Controller/AdminOfferController.php
  templates/adminOffer/_delete_form.html.twig
  templates/adminOffer/new.html.twig
Labels: Reviewed

#246 add placeholders
  src/Form/EcosystemType.php
  src/Form/MembershipType.php
  src/Form/RegistrationFormType.php
Labels: Reviewed

#247 fix bug when status is null
  templates/admin/ecosystem/index.html.twig
  templates/admin/ecosystem/show.html.twig
Labels: Reviewed

#249 form select order by ASC
  src/Form/EcosystemSearchType.php
  src/Form/EcosystemType.php
  src/Form/ProjectType.php
  src/Form/TestimonyType.php
Labels: Reviewed

#250 Fix cooz
  assets/styles/companies.scss
  src/Controller/CooperativeController.php
  templates/cooperative/companies.html.twig
  templates/cooperative/projectSheet.html.twig
  templates/cooperative/projects.html.twig
  templates/cooperative/show_company.html.twig
  templates/home/index.html.twig
Labels: Reviewed

#251 pagination project
  assets/styles/projects.scss
  src/Controller/CooperativeController.php
  templates/cooperative/projects.html.twig
Labels: Reviewed

#252 remove a border radius
  assets/styles/app.scss
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/includes/_mobilebanner.html.twig
Labels: Reviewed

#253 Fixed navbars when user is just ROLE_USER
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
Labels: Reviewed

#254 fix margin between testimony and price on service page
  templates/offer/index.html.twig
Labels: Reviewed

#256 animation on refresh button
  templates/cooperative/companies.html.twig
Labels: Reviewed

#257 dev to master
  assets/images/bg.jpg
  assets/styles/app.scss
  assets/styles/companies.scss
  assets/styles/contact.scss
  assets/styles/error.scss
  assets/styles/home.scss
  assets/styles/login.scss
  assets/styles/offer.scss
  assets/styles/profile.scss
  assets/styles/projects.scss
  assets/styles/register.scss
  assets/styles/testimony.scss
  public/uploads/favicon-6006f90c4bccc330410399.png
  src/Controller/AdminOfferController.php
  src/Controller/CooperativeController.php
  src/DataFixtures/EcosystemeFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Form/EcosystemSearchType.php
  src/Form/EcosystemType.php
  src/Form/MembershipType.php
  src/Form/ProjectType.php
  src/Form/RegistrationFormType.php
  src/Form/TestimonyType.php
  templates/admin/ecosystem/index.html.twig
  templates/admin/ecosystem/show.html.twig
  templates/adminOffer/_delete_form.html.twig
  templates/adminOffer/new.html.twig
  templates/bundles/TwigBundle/Exception/error401.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/cooperative/companies.html.twig
  templates/cooperative/projectSheet.html.twig
  templates/cooperative/projects.html.twig
  templates/cooperative/show_company.html.twig
  templates/home/index.html.twig
  templates/includes/_mobilebanner.html.twig
  templates/includes/_navbar.html.twig
  templates/includes/_navbarmobile.html.twig
  templates/offer/index.html.twig
  webpack.config.js
Labels: Reviewed

#260 Changed labels, MDP button and added competences to the profile
  src/Form/MembershipType.php
  templates/security/profile.html.twig
Labels: Reviewed

#258 change if example
  templates/offer/index.html.twig
Labels: Reviewed

#261 add redirection for admin
  assets/styles/companies.scss
  assets/styles/projects.scss
  src/Controller/CooperativeController.php
  templates/cooperative/companies.html.twig
Labels: Reviewed

#259 change path ecosystem on homepage admin
  templates/admin/home/index.html.twig
Labels: Reviewed

#262 dev to master
  assets/styles/companies.scss
  assets/styles/projects.scss
  src/Controller/CooperativeController.php
  src/Form/MembershipType.php
  templates/admin/home/index.html.twig
  templates/cooperative/companies.html.twig
  templates/offer/index.html.twig
  templates/security/profile.html.twig
Labels: Reviewed

#263 change some css
  assets/styles/home.scss
  templates/cooperative/companies.html.twig
  templates/cooperative/projects.html.twig
  templates/home/index.html.twig
  templates/security/profile.html.twig
Labels: Reviewed

#265 add optionnel on form
  src/Form/EcosystemType.php
  src/Form/MembershipType.php
  src/Form/OfferType.php
Labels: Reviewed

#264 J'ai pas de tête donc j'espère que ça passe en fix...
  src/Controller/SecurityController.php
  templates/cooperative/companyEmail.html.twig
  templates/security/profilEmail.html.twig
Labels: Corrections done, Reviewed

#266 dernière dev to master de la journée :)
  assets/styles/home.scss
  src/Controller/SecurityController.php
  src/Form/EcosystemType.php
  src/Form/MembershipType.php
  src/Form/OfferType.php
  templates/cooperative/companies.html.twig
  templates/cooperative/companyEmail.html.twig
  templates/cooperative/projects.html.twig
  templates/home/index.html.twig
  templates/security/profilEmail.html.twig
  templates/security/profile.html.twig
Labels: Reviewed

#268 fix StatusFilterType
  src/Form/StatusFilterType.php
Labels: Reviewed

#269 add no project when there are none
  templates/cooperative/projects.html.twig
Labels: Reviewed

#267 Fixed redirection considering user role and if a company exists with …
  src/Controller/SecurityController.php
Labels: Conflicts resolved, Reviewed

#270 fix page 404
  templates/bundles/TwigBundle/Exception/error404.html.twig
Labels: Reviewed

#271 Update README.md
  README.md
Labels: Reviewed

#274 add ck editor to yarn
  package.json
  yarn.lock
Labels: Reviewed

#272 fix the home page section
  assets/styles/home.scss
  templates/home/index.html.twig
Labels: Reviewed
